### ISSUE TITLE
System.Object[] issue

### ISSUE THREAD

**Issue by Beercow** [olafhartong/ATTACKdatamap#1]
When running Invoke-ATTACK-UpdateExcel, majority of the ID column contains System.Object[] instead of the ID number.

**Comment by olafhartong** [comment]
can you give more context? 
PS version, OS, Excel version ?

Just tested it on a fresh VM with office 2013 and it works fine, even the new tactics and techniques.
Will post an update later

**Comment by Beercow** [comment]
PS version:
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      16299  1004

OS:
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      16299  0

Excel:
Microsoft Office 365 ProPlus - en-us 16.0.10730.20334

**Comment by Beercow** [comment]
$Collection | Select-Object {$_.ID -split ","}
{T1156, }
{T1134, , , ...}
{T1015, CAPEC-558, , ...}
{T1087, CAPEC-575}
{T1098, , , }
{T1182, , , }
{T1103, , , ...}
{T1155, }
{T1017, CAPEC-187}
{T1138, , }
T1010
T1123
{T1131, , , }
T1119
T1020
{T1197, , , ...}
{T1139, }
{T1009, CAPEC-572}
{T1067, , }
T1217
{T1176, , , ...}
{T1110, , , ...}
{T1088, , , ...}
{T1191, , , ...}
{T1042, CAPEC-556, , ...}
T1146
{T1115, , }
{T1116, , , ...}
{T1059, }
{T1043, }
T1092
{T1500, , }
{T1223, , , ...}
{T1109, , , }
{T1122, , , }
{T1090, , }
{T1196, , , ...}
{T1136, }
{T1003, CAPEC-567, , ...}
{T1081, CAPEC-545, , }
{T1214, }
{T1094, }
{T1024, , , }
{T1207, , , ...}
{T1038, CAPEC-471, , ...}
{T1073, , }
{T1002, }
{T1485, , , ...}
{T1132, , , }
{T1022, , }
{T1486, , , ...}
{T1001, }
T1074
{T1030, }
{T1213, , }
T1005
T1039
T1025
{T1491, , , ...}
{T1140, , , }
{T1089, CAPEC-578}
{T1488, , , }
{T1487, , , ...}
{T1175, , , ...}
{T1172, }
{T1483, , , ...}
{T1482, , , ...}
{T1189, }
{T1157, , }
{T1173, , , ...}
T1114
{T1499, CAPEC-227, CAPEC-131, CAPEC-130...}
{T1480, , , ...}
{T1106, , }
{T1129, }
{T1048, }
{T1041, }
T1011
T1052
{T1190, , , ...}
T1203
{T1212, , }
T1211
{T1068, CAPEC-69}
{T1210, , , ...}
{T1133, }
{T1181, , , ...}
{T1008, }
{T1107, }
{T1222, , , ...}
{T1006, , }
{T1044, CAPEC-17, , }
{T1083, }
{T1495, , }
{T1187, , , ...}
{T1144, , , ...}
{T1061, }
{T1484, , , ...}
T1148
{T1200, , , ...}
{T1158, , , }
{T1147, }
{T1143, }
{T1179, , , ...}
{T1062, CAPEC-552, , ...}
{T1183, , , ...}
{T1054, CAPEC-571, }
T1066
{T1070, CAPEC-93, , ...}
{T1202, , , }
{T1490, , }
{T1056, CAPEC-569, , ...}
{T1141, , , ...}
{T1130, , , ...}
{T1118, , }
{T1208, , , ...}
{T1215, , , ...}
{T1142, , }
{T1161, , }
{T1149, , }
{T1171, , , ...}
{T1177, , , ...}
{T1159, , , ...}
{T1160, , , ...}
{T1152, }
{T1168, , , ...}
{T1162, , , ...}
{T1037, CAPEC-564, , }
{T1185, , , ...}
{T1036, , , ...}
{T1031, CAPEC-551, , ...}
{T1112, , , ...}
{T1170, , , ...}
T1104
T1188
{T1026, }
{T1079, , , ...}
{T1096, , , ...}
{T1128, , , }
{T1498, , , ...}
T1046
{T1126, }
{T1135, , }
{T1040, CAPEC-158}
{T1050, CAPEC-550, , ...}
{T1027, , , ...}
{T1137, , , ...}
{T1075, }
{T1097, , , ...}
{T1174, , }
{T1201, , }
{T1034, CAPEC-159, , ...}
T1120
{T1069, CAPEC-576}
{T1150, }
{T1205, }
{T1013, , , }
{T1086, , , ...}
{T1145, , , }
{T1057, CAPEC-573}
{T1186, , , ...}
{T1093, , }
{T1055, CAPEC-242, , ...}
{T1012, }
{T1163, , }
{T1164, }
{T1108, }
{T1060, CAPEC-270, , ...}
{T1121, , , }
{T1117, , , ...}
{T1219, , , }
{T1076, CAPEC-555, , ...}
{T1105, }
{T1021, CAPEC-555}
T1018
T1091
{T1496, }
{T1014, , , ...}
{T1085, , }
{T1494, , }
{T1178, , , ...}
{T1198, , , ...}
{T1184, , , ...}
{T1053, CAPEC-557, , ...}
T1029
{T1113, }
{T1180, , }
{T1064, , , ...}
T1063
{T1101, , }
{T1167, , , }
T1035
{T1058, CAPEC-203, , ...}
{T1489, , , }
{T1166, , }
{T1051, CAPEC-563, , ...}
T1023
{T1218, , , ...}
{T1216, , }
{T1045, CAPEC-570, }
T1153
{T1151, }
{T1193, CAPEC-163}
{T1192, CAPEC-163}
{T1194, CAPEC-163}
{T1071, }
{T1032, , , ...}
{T1095, , , }
{T1165, , }
{T1492, , }
{T1169, }
{T1206, , }
{T1195, CAPEC-437, CAPEC-438, CAPEC-439...}
{T1019, CAPEC-532, , ...}
{T1082, CAPEC-311}
{T1016, CAPEC-309}
T1049
{T1033, CAPEC-577}
{T1007, CAPEC-574}
{T1124, , , }
{T1501, , , ...}
{T1080, CAPEC-562, }
{T1221, , , ...}
T1072
{T1209, , , ...}
{T1099, }
{T1493, , }
T1154
{T1127, , , ...}
T1199
{T1111, , , }
{T1065, }
T1204
{T1078, CAPEC-560, , ...}
{T1125, }
{T1497, , , ...}
{T1102, }
{T1100, , }
{T1077, CAPEC-561, , ...}
{T1047, , , ...}
{T1084, , , ...}
{T1028, , }
{T1004, CAPEC-579, , }
{T1220, , , ...}

**Comment by Sorakurai** [comment]
I'm having the same issue as Beercow;  the External IDs sometimes contain multiple values ...
Adjusting the 'ID' property in $Props as follows, fixes the issue for me (dirty solution though):

`'ID' = $object | Select-Object -ExpandProperty external_references | Where-Object source_name -eq "mitre-attack" | Select-Object -ExpandProperty external_id`

**Comment by olafhartong** [comment]
fixed!
