### ISSUE TITLE
Small typo

### ISSUE THREAD

**Issue by fl1bbl3** [olafhartong/ATTACKdatamap#2]
The psm file has a missing hyphen.

ATTACKdatamap.psd1:        'Invoke-ATTACK-UpdateExcel',
ATTACKdatamap.psm1:function Invoke-ATTACKUpdateExcel {

**Comment by olafhartong** [comment]
thanks for reminding me, I changed it in the psm to it have a proper PowerShell syntax, but didn't remove it in the psd.
I also forgot to add the new modules, which are there now.
